In [12]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [21]:
import pandas as pd

# Spécifiez le chemin complet vers le fichier CSV
chemin_fichier_csv = "/content/drive/My Drive/Télémedecine/lou_total.csv"

# Lisez le fichier CSV en spécifiant le délimiteur comme '\t' (tabulation)
data = pd.read_csv(chemin_fichier_csv, delimiter="\t", header=None)

# Sélectionnez uniquement les colonnes 2, 3 et 4
data = data.iloc[:, 2:5]

# Renommez les colonnes
data.columns = ['THORAX', 'X', 'Y']

# Affichez le DataFrame mis à jour
print(data)

       THORAX      X      Y
0       29496  34114  37228
1       29832  34104  37248
2       30136  34120  37260
3       30360  34128  37224
4       30436  34120  37216
...       ...    ...    ...
31165   22048  34576  36988
31166   22266  34544  36992
31167   22480  34560  37000
31168   22700  34570  36984
31169   22920  34556  36984

[31170 rows x 3 columns]

In [25]:
# Calcul des fonctions de transfert
# Appliquer la fonction de transfert à chaque valeur de la colonne "X"
data['X'] = data['X'].apply(lambda x: (((x / (2**16 - 1)) - 0.5) * 3))

# Appliquer la fonction de transfert à chaque valeur de la colonne "Y"
data['Y'] = data['Y'].apply(lambda y: (((y / (2**16 - 1)) - 0.5) * 3))

print(data)

       THORAX         X         Y
0       29496 -1.500069 -1.500069
1       29832 -1.500069 -1.500069
2       30136 -1.500069 -1.500069
3       30360 -1.500069 -1.500069
4       30436 -1.500069 -1.500069
...       ...       ...       ...
31165   22048 -1.500069 -1.500069
31166   22266 -1.500069 -1.500069
31167   22480 -1.500069 -1.500069
31168   22700 -1.500069 -1.500069
31169   22920 -1.500069 -1.500069

[31170 rows x 3 columns]